kind: pipeline
type: docker
name: Kernel Compiling
steps: 
  - 
    commands: 
      - "bash ./run.sh"
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
      GITHUB_TOKEN:
        from_secret: GH_TOKEN
      GITHUB_EMAIL:
        from_secret: GH_EMAIL
      GITHUB_USERNAME:
        from_secret: GH_USERNAME
    image: alpine
    name: Compilation
    when: 
      branch: 
        - perf
