--- 
clone: 
  depth: 1
kind: pipeline
name: Brutal Kernel Compilation
steps: 
  - 
    commands: 
      - "bash ./run.sh"
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
      GITHUB_TOKEN:
        from_secret: GH_TOKEN
      GITHUB_EMAIL:
        from_secret: GH_EMAIL
      GITHUB_USERNAME:
        from_secret: GH_USERNAME
    image: fadlyas/kernel_dockerfile:latest
    name: Compilation
    trigger: 
      branch: 
        - unified-tes
