version: 2.1
jobs:
  compile:
   docker:
      - image: fadlyas/kernel_dockerfile:latest
   steps:
      - run:
          no_output_timeout: 30m 
          command: |
            git clone https://github.com/dimas-ady/kernel-builder-droneci
            ls
            ls ~/project
            cd kernel-builder-droneci
            bash run2.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
