version: 2.1
jobs:
  compile:
   docker:
      - image: fadlyas/kernel_dockerfile:latest
   steps:
      - run:
          no_output_timeout: 30m 
          command: |
            source run.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
